# Generated by Django 5.2.4 on 2025-07-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nick', models.CharField(max_length=255)),
                ('lane', models.CharField(max_length=255)),
                ('champion', models.CharField(max_length=255)),
                ('team_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SummonerNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_names', to='FMS_Django_App.players')),
            ],
        ),
    ]
