# Generated by Django 5.2.4 on 2025-07-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS_Django_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20)),
                ('summoner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='FMS_Django_App.summonernames')),
            ],
        ),
    ]
