# Generated by Django 5.2.4 on 2025-07-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS_Django_App', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nick',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
