# Generated by Django 5.2.4 on 2025-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS_Django_App', '0004_alter_users_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
