# Generated by Django 5.2.4 on 2025-07-28 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS_Django_App', '0005_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='summoner_name',
        ),
        migrations.AddField(
            model_name='matches',
            name='game_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='game_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='MatchParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=50)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('win', models.BooleanField()),
                ('lane', models.CharField(max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='FMS_Django_App.matches')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='FMS_Django_App.summonernames')),
            ],
        ),
    ]
