# Generated by Django 5.2.4 on 2025-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS_Django_App', '0006_remove_matches_summoner_name_matches_game_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummonerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(max_length=255)),
                ('puuid', models.CharField(db_index=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nick', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='USER', max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
        migrations.RemoveField(
            model_name='summonernames',
            name='player',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.AddField(
            model_name='summonername',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_names', to='FMS_Django_App.player'),
        ),
        migrations.AlterField(
            model_name='matchparticipation',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='FMS_Django_App.summonername'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='FMS_Django_App.user'),
        ),
        migrations.DeleteModel(
            name='SummonerNames',
        ),
    ]
