name: Fetch Matches

on:
  schedule:
    - cron: '*/30 * * * *'  # co 30 minut
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_matches
        run: python manage.py fetch_matches
